include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  language:
    strict-inference: true
    strict-raw-types: true

# linter のルール一覧は下記 URL を参照
# https://dart-lang.github.io/linter/lints/
linter:
  rules:
    ### Error Rules ######################################
    - avoid_dynamic_calls
    - avoid_slow_async_io
    - avoid_type_to_string
    - comment_references
    - control_flow_in_finally
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - throw_in_finally
    - unnecessary_statements
    ### Style Rules ######################################
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_classes_with_only_static_members
    - avoid_final_parameters
    - avoid_function_literals_in_foreach_calls
    - avoid_init_to_null
    - avoid_multiple_declarations_per_line
    - avoid_positional_boolean_parameters
    - avoid_private_typedef_functions
    - avoid_redundant_argument_values
    - avoid_returning_null
    - avoid_returning_this
    - avoid_types_on_closure_parameters
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - directives_ordering
    - empty_constructor_bodies
    - eol_at_end_of_file
    - flutter_style_todos
    - omit_local_variable_types
    - one_member_abstracts
    - only_throw_errors
    - package_api_docs
    - parameter_assignments
    - prefer_collection_literals
    - prefer_contains
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_single_quotes
    - sized_box_shrink_expand
    - sort_unnamed_constructors_first
    - unawaited_futures
    - unnecessary_this
    - use_colored_box
    - use_decorated_box
    - use_enums
    - use_named_constants
    - use_string_buffers
    - use_super_parameters
    - use_test_throws_matchers
